apiVersion: v1
kind: Service
metadata:
  name: favorite-go
spec:
  type: ClusterIP

  selector:
    app: favorite-go

  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP