name: Manage Ingress Controller instances

on:
  workflow_dispatch:
jobs:
  deploy-ingress-with-custom-http-snippet-config-map:
    runs-on: ubuntu-latest
    environment: ingress-nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ci-cluster

      - name: Verify cluster
        run: kubectl get nodes

      - name: Helm install with secret http-snippet
        env:
          HTTP_SNIPPET: ${{ secrets.HTTP_SNIPPET }}
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

          # Escape newlines as literal \n
          SNIPPET_ESCAPED=$(printf "%s" "$HTTP_SNIPPET" | awk '{printf "%s\\n", $0}')
          
          echo "######printing scaped -> $SNIPPET_ESCAPED"

          echo "Installing ingress-nginx with http-snippet via --set-string"

          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --version 4.13.2 \
            --values ingress/values.yaml \
            --set-string controller.config.http-snippet="$SNIPPET_ESCAPED"

      - name: Verify install with config map from environment secret
        run: |
          kubectl get cm ingress-nginx-controller -o yaml -n ingress-nginx