name: Manage Ingress Controller instances

on:
  workflow_dispatch:
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment: ingress-nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ci-cluster

      - name: Verify cluster
        run: kubectl get nodes

      - name: format secret http-snippet
        env:
          HTTP_SNIPPET: ${{ secrets.HTTP_SNIPPET }}
        run:  SNIPPET_ESCAPED=$(printf "%s" "$HTTP_SNIPPET" | sed ':a;N;$!ba;s/\n/\\n/g')

      - name: Helm install
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --version 4.13.2 \
            --values ingress/values.yaml \
            --set controller.config.http-snippet="$SNIPPET_ESCAPED"

      - name: Verify install
        run: |
          kubectl get cm -n ingress-nginx