name: Manage Ingress Controller instances

on:
  workflow_dispatch:
jobs:
  deploy-ingress-nginx:
    runs-on: ubuntu-latest
    environment: ingress-nginx
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kind (Kubernetes in Docker)
        uses: helm/kind-action@v1.9.0

      - name: Create temporary file for http-snippet
        run: |
          mkdir -p tmp
          # Write the secret into the file exactly as-is
          printf "%s\n" "${{ secrets.NGINX_HTTP_SNIPPET }}" > tmp/http-snippet.conf
          echo "===== snippet content ====="
          cat tmp/http-snippet.conf
          echo "==========================="

      - name: Add ingress-nginx repo
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Install ingress-nginx with Helm using secret snippet
        run: |
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --version 4.13.2 \
            --values ingress/values.yaml \
            --set-file controller.config.http-snippet=tmp/http-snippet.conf

      - name: Wait for ingress-nginx pods to be ready
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=Ready pods \
            --selector=app.kubernetes.io/component=controller \
            --timeout=180s

      - name: Verify ConfigMap content
        run: |
          echo "===== ingress-nginx-controller ConfigMap ====="
          kubectl get configmap ingress-nginx-controller -n ingress-nginx -o yaml | grep -A 20 "http-snippet:"
          echo "=============================================="