name: Manage Ingress Controller instances

on:
  workflow_dispatch:
jobs:
  deploy-ingress-with-custom-http-snippet-config-map:
    runs-on: ubuntu-latest
    environment: ingress-nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ci-cluster

      - name: Verify cluster
        run: kubectl get nodes

      - name: Deploy ingress-nginx with secret snippet
        env:
          HTTP_SNIPPET: ${{ vars.HTTP_SNIPPET }}
        run: |
          # Write the secret value to a temporary file
          echo "$HTTP_SNIPPET" > snippet.txt

          echo "Installing ingress-nginx with http-snippet via --set-string"

          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --version 4.13.2 \
            --values ingress/values.yaml \
            --set-file controller.config.http-snippet=snippet.txt

      - name: Verify install with config map from environment secret
        run: |
          kubectl get cm ingress-nginx-controller -o yaml -n ingress-nginx