name: Manage Ingress Controller instances

on:
  workflow_dispatch:
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment: ingress-nginx
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ci-cluster

      - name: Verify cluster
        run: kubectl get nodes

      - name: Helm install
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace
            --version 4.13.2 \
            --values ingress/values.yaml
            --set controller.config.http-snippet = ${{ secrets.HTTP_SNIPPET }}

      - name: Verify install
        run: kubectl get all